apiVersion: v1
kind: Service
metadata:
  name: latent-api-service
spec:
  type: NodePort
  selector:
    app: latent-api
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30000
      targetPort: 5000