apiVersion: apps/v1
kind: Deployment
metadata:
  name: latent-api-deployment
  labels:
    app: latent-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: latent-api
  template:
    metadata:
      labels:
        app: latent-api
    spec:
      containers:
      - name: api
        image: api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000