apiVersion: v1
kind: Service
metadata:
  name: latent-worker-service
spec:
  type: NodePort
  selector:
    app: latent-worker
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30000
      targetPort: 5000